// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexumDevs.VitalTrek.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace NexumDevs.VitalTrek.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620190314_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Engagement.Domain.Model.Aggregates.GamificationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<Guid>("TouristId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("TouristId")
                        .IsUnique();

                    b.ToTable("GamificationProfiles", (string)null);
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Engagement.Domain.Model.Entities.AwardedExpedition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("AwardedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ExpeditionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "ExpeditionId")
                        .IsUnique();

                    b.ToTable("AwardedExpeditions", (string)null);
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Monitoring.Domain.Model.Aggregate.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("acknowledged_at");

                    b.Property<int?>("AcknowledgedBy")
                        .HasColumnType("int")
                        .HasColumnName("acknowledged_by");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int")
                        .HasColumnName("expedition_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<int>("Severity")
                        .HasColumnType("int")
                        .HasColumnName("severity");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("TouristId")
                        .HasColumnType("int")
                        .HasColumnName("tourist_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_alerts");

                    b.ToTable("alerts");
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Monitoring.Domain.Model.Aggregate.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int")
                        .HasColumnName("expedition_id");

                    b.Property<string>("ReportedAt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reported_at");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("int")
                        .HasColumnName("reported_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_incidents");

                    b.ToTable("incidents");
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Monitoring.Domain.Model.Entities.LocationReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("AccuracyMeters")
                        .HasColumnType("double")
                        .HasColumnName("accuracy_meters");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int")
                        .HasColumnName("expedition_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<int>("TouristId")
                        .HasColumnType("int")
                        .HasColumnName("tourist_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_location_readings");

                    b.ToTable("location_readings");
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Monitoring.Domain.Model.Entities.VitalSignReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("BloodOxygen")
                        .HasColumnType("double")
                        .HasColumnName("blood_oxygen");

                    b.Property<double>("BodyTemperature")
                        .HasColumnType("double")
                        .HasColumnName("body_temperature");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int")
                        .HasColumnName("expedition_id");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int")
                        .HasColumnName("heart_rate");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<int>("TouristId")
                        .HasColumnType("int")
                        .HasColumnName("tourist_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_vital_sign_readings");

                    b.ToTable("vital_sign_readings");
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Navigation.Domain.Model.Aggregates.Expedition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpeditionName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("expedition_name");

                    b.Property<int>("GuideID")
                        .HasColumnType("int")
                        .HasColumnName("guide_i_d");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<int>("TourID")
                        .HasColumnType("int")
                        .HasColumnName("tour_i_d");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_expeditions");

                    b.ToTable("expeditions");
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Navigation.Domain.Model.Aggregates.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpeditionID")
                        .HasColumnType("int")
                        .HasColumnName("expedition_i_d");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("media_url");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<int>("TouristID")
                        .HasColumnType("int")
                        .HasColumnName("tourist_i_d");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_experiences");

                    b.HasIndex("ExpeditionID")
                        .HasDatabaseName("i_x_experiences_expedition_i_d");

                    b.ToTable("experiences");
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Navigation.Domain.Model.Aggregates.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CompletedCheckpoints")
                        .HasColumnType("int")
                        .HasColumnName("completed_checkpoints");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int")
                        .HasColumnName("expedition_id");

                    b.Property<double>("Percentage")
                        .HasColumnType("double")
                        .HasColumnName("percentage");

                    b.Property<int>("TotalCheckpoints")
                        .HasColumnType("int")
                        .HasColumnName("total_checkpoints");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_progresses");

                    b.HasIndex("ExpeditionId")
                        .HasDatabaseName("i_x_progresses_expedition_id");

                    b.ToTable("progresses");
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Navigation.Domain.Model.Aggregates.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("condition");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int")
                        .HasColumnName("expedition_id");

                    b.Property<double>("Humidity")
                        .HasColumnType("double")
                        .HasColumnName("humidity");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("double")
                        .HasColumnName("temperature_celsius");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<double>("WindSpeedKmh")
                        .HasColumnType("double")
                        .HasColumnName("wind_speed_kmh");

                    b.HasKey("Id")
                        .HasName("p_k_weathers");

                    b.HasIndex("ExpeditionId")
                        .HasDatabaseName("i_x_weathers_expedition_id");

                    b.ToTable("weathers");
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Navigation.Domain.Model.Entities.BinnacleReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int")
                        .HasColumnName("expedition_id");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("media_url");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<int>("TouristId")
                        .HasColumnType("int")
                        .HasColumnName("tourist_id");

                    b.HasKey("Id")
                        .HasName("p_k_binnacle_readings");

                    b.ToTable("binnacle_readings");
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Engagement.Domain.Model.Entities.AwardedExpedition", b =>
                {
                    b.HasOne("NexumDevs.VitalTrek.Platform.Engagement.Domain.Model.Aggregates.GamificationProfile", null)
                        .WithMany("AwardedExpeditions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Navigation.Domain.Model.Aggregates.Experience", b =>
                {
                    b.HasOne("NexumDevs.VitalTrek.Platform.Navigation.Domain.Model.Aggregates.Expedition", "Expedition")
                        .WithMany()
                        .HasForeignKey("ExpeditionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_experiences_expeditions_expedition_i_d");

                    b.Navigation("Expedition");
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Navigation.Domain.Model.Aggregates.Progress", b =>
                {
                    b.HasOne("NexumDevs.VitalTrek.Platform.Navigation.Domain.Model.Aggregates.Expedition", "Expedition")
                        .WithMany()
                        .HasForeignKey("ExpeditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_progresses_expeditions_expedition_id");

                    b.Navigation("Expedition");
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Navigation.Domain.Model.Aggregates.Weather", b =>
                {
                    b.HasOne("NexumDevs.VitalTrek.Platform.Navigation.Domain.Model.Aggregates.Expedition", "Expedition")
                        .WithMany()
                        .HasForeignKey("ExpeditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_weathers_expeditions_expedition_id");

                    b.Navigation("Expedition");
                });

            modelBuilder.Entity("NexumDevs.VitalTrek.Platform.Engagement.Domain.Model.Aggregates.GamificationProfile", b =>
                {
                    b.Navigation("AwardedExpeditions");
                });
#pragma warning restore 612, 618
        }
    }
}
